meta_product_name: "Share A Meal"
meta_title: "Share a Meal- Never be bored of your food again!"
meta_description: "A completely free app where you can exchange meals as form of payment"
meta_image: "share_a_meal.png" # should exist in `app/assets/images/`
